# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_acf <- function(x, max_lag = 20L, normalize = TRUE) {
    .Call(`_tsdiscov_cpp_acf`, x, max_lag, normalize)
}

cpp_acf_first_min <- function(x, max_lag = 20L) {
    .Call(`_tsdiscov_cpp_acf_first_min`, x, max_lag)
}

cpp_acf_timescale <- function(x, max_lag = 20L) {
    .Call(`_tsdiscov_cpp_acf_timescale`, x, max_lag)
}

cpp_acf_features <- function(x, max_lag = 20L) {
    .Call(`_tsdiscov_cpp_acf_features`, x, max_lag)
}

cpp_absolute_sum_of_changes <- function(x) {
    .Call(`_tsdiscov_cpp_absolute_sum_of_changes`, x)
}

cpp_range <- function(x) {
    .Call(`_tsdiscov_cpp_range`, x)
}

cpp_median_absolute_deviation <- function(x) {
    .Call(`_tsdiscov_cpp_median_absolute_deviation`, x)
}

cpp_coefficient_of_variation <- function(x) {
    .Call(`_tsdiscov_cpp_coefficient_of_variation`, x)
}

cpp_benford_correlation <- function(x) {
    .Call(`_tsdiscov_cpp_benford_correlation`, x)
}

cpp_automutual_info_lag2 <- function(x, num_bins = 5L) {
    .Call(`_tsdiscov_cpp_automutual_info_lag2`, x, num_bins)
}

cpp_automutual_info_first_min <- function(x, max_lag = 40L, num_bins = 10L) {
    .Call(`_tsdiscov_cpp_automutual_info_first_min`, x, max_lag, num_bins)
}

cpp_embedding_dist_exp_fit <- function(x) {
    .Call(`_tsdiscov_cpp_embedding_dist_exp_fit`, x)
}

cpp_dfa <- function(x) {
    .Call(`_tsdiscov_cpp_dfa`, x)
}

cpp_rs_range <- function(x) {
    .Call(`_tsdiscov_cpp_rs_range`, x)
}

cpp_periodicity_wang <- function(x) {
    .Call(`_tsdiscov_cpp_periodicity_wang`, x)
}

cpp_mean <- function(x) {
    .Call(`_tsdiscov_cpp_mean`, x)
}

cpp_std <- function(x) {
    .Call(`_tsdiscov_cpp_std`, x)
}

cpp_variance <- function(x) {
    .Call(`_tsdiscov_cpp_variance`, x)
}

cpp_skewness <- function(x) {
    .Call(`_tsdiscov_cpp_skewness`, x)
}

cpp_kurtosis <- function(x) {
    .Call(`_tsdiscov_cpp_kurtosis`, x)
}

cpp_quantile <- function(x, probs) {
    .Call(`_tsdiscov_cpp_quantile`, x, probs)
}

cpp_histogram_mode_5 <- function(x) {
    .Call(`_tsdiscov_cpp_histogram_mode_5`, x)
}

cpp_histogram_mode_10 <- function(x) {
    .Call(`_tsdiscov_cpp_histogram_mode_10`, x)
}

cpp_outlier_timing <- function(x, positive = TRUE, threshold = 0.01) {
    .Call(`_tsdiscov_cpp_outlier_timing`, x, positive, threshold)
}

cpp_outlier_timing_pos <- function(x) {
    .Call(`_tsdiscov_cpp_outlier_timing_pos`, x)
}

cpp_outlier_timing_neg <- function(x) {
    .Call(`_tsdiscov_cpp_outlier_timing_neg`, x)
}

cpp_long_stretch <- function(x, above_mean = TRUE) {
    .Call(`_tsdiscov_cpp_long_stretch`, x, above_mean)
}

cpp_stretch_high <- function(x) {
    .Call(`_tsdiscov_cpp_stretch_high`, x)
}

cpp_stretch_low <- function(x) {
    .Call(`_tsdiscov_cpp_stretch_low`, x)
}

cpp_transition_variance <- function(x, num_bins = 3L) {
    .Call(`_tsdiscov_cpp_transition_variance`, x, num_bins)
}

#' @title Number of crossing points (median crossings)
#' @description Computes the number of times a time series crosses its median
#' @param x Numeric vector (time series)
#' @return Number of median crossings
#' @export
cpp_crossing_points <- function(x) {
    .Call(`_tsdiscov_cpp_crossing_points`, x)
}

#' @title Longest flat spot
#' @description Maximum run length within any of 10 equal-sized bins
#' @param x Numeric vector (time series)
#' @return Maximum run length in any bin
#' @export
cpp_flat_spots <- function(x) {
    .Call(`_tsdiscov_cpp_flat_spots`, x)
}

#' @title 2D embedding - proportion of points inside circle
#' @description Points inside given circular boundary in 2-d embedding space
#' @param y Numeric vector (time series)
#' @param boundary Circular boundary (1 or 2)
#' @return Proportion of points inside circle
#' @export
cpp_embed2_incircle <- function(y, boundary) {
    .Call(`_tsdiscov_cpp_embed2_incircle`, y, boundary)
}

#' @title Binary motif entropy (3-letter words)
#' @description Entropy of 3-letter binary words (above/below mean)
#' @param y Numeric vector (time series)
#' @return Entropy of binary motifs
#' @export
cpp_motiftwo_entro3 <- function(y) {
    .Call(`_tsdiscov_cpp_motiftwo_entro3`, y)
}

#' @title Walker crossing proportion
#' @description Simulates a walker moving through time domain
#' @param y Numeric vector (time series)
#' @return Proportion of crossings between walker and time series
#' @export
cpp_walker_propcross <- function(y) {
    .Call(`_tsdiscov_cpp_walker_propcross`, y)
}

cpp_diff <- function(x, lag = 1L, differences = 1L) {
    .Call(`_tsdiscov_cpp_diff`, x, lag, differences)
}

cpp_diff1_acf1 <- function(x) {
    .Call(`_tsdiscov_cpp_diff1_acf1`, x)
}

cpp_diff1_acf10 <- function(x) {
    .Call(`_tsdiscov_cpp_diff1_acf10`, x)
}

cpp_diff2_acf1 <- function(x) {
    .Call(`_tsdiscov_cpp_diff2_acf1`, x)
}

cpp_diff2_acf10 <- function(x) {
    .Call(`_tsdiscov_cpp_diff2_acf10`, x)
}

cpp_diff1x_pacf5 <- function(x) {
    .Call(`_tsdiscov_cpp_diff1x_pacf5`, x)
}

cpp_diff2x_pacf5 <- function(x) {
    .Call(`_tsdiscov_cpp_diff2x_pacf5`, x)
}

cpp_diff_acf_features <- function(x) {
    .Call(`_tsdiscov_cpp_diff_acf_features`, x)
}

cpp_sample_entropy <- function(x, m = 2L, r = 0.2) {
    .Call(`_tsdiscov_cpp_sample_entropy`, x, m, r)
}

cpp_approximate_entropy <- function(x, m = 2L, r = 0.2) {
    .Call(`_tsdiscov_cpp_approximate_entropy`, x, m, r)
}

cpp_permutation_entropy <- function(x, m = 3L, tau = 1L) {
    .Call(`_tsdiscov_cpp_permutation_entropy`, x, m, tau)
}

cpp_shannon_entropy <- function(x, num_bins = 10L) {
    .Call(`_tsdiscov_cpp_shannon_entropy`, x, num_bins)
}

cpp_multiscale_entropy <- function(x, scales = as.integer( c(2, 5)), m = 2L, r = 0.2) {
    .Call(`_tsdiscov_cpp_multiscale_entropy`, x, scales, m, r)
}

cpp_forecast_error_mean3 <- function(x) {
    .Call(`_tsdiscov_cpp_forecast_error_mean3`, x)
}

cpp_timescale_ratio_after_whitening <- function(x) {
    .Call(`_tsdiscov_cpp_timescale_ratio_after_whitening`, x)
}

cpp_time_reversibility <- function(x) {
    .Call(`_tsdiscov_cpp_time_reversibility`, x)
}

cpp_high_fluctuation_prop <- function(x) {
    .Call(`_tsdiscov_cpp_high_fluctuation_prop`, x)
}

cpp_arch_acf <- function(x) {
    .Call(`_tsdiscov_cpp_arch_acf`, x)
}

cpp_firstzero_ac <- function(x, max_lag = 50L) {
    .Call(`_tsdiscov_cpp_firstzero_ac`, x, max_lag)
}

cpp_zero_proportion <- function(x, tol = 1e-8) {
    .Call(`_tsdiscov_cpp_zero_proportion`, x, tol)
}

cpp_std1st_der <- function(x) {
    .Call(`_tsdiscov_cpp_std1st_der`, x)
}

cpp_motif_three_quantile <- function(x) {
    .Call(`_tsdiscov_cpp_motif_three_quantile`, x)
}

#' Compute pairwise cross-correlation function (CCF) features - Rcpp version
#'
#' Efficiently computes CCF for all pairs of time series
#'
#' @param X Matrix (N x T) where rows are series, columns are timepoints
#' @param max_lag Maximum lag for CCF
#' @return List with ccf_max_vals, ccf_lag_vals, ccf_zero_vals for all pairs
#' @keywords internal
cpp_pairwise_ccf <- function(X, max_lag) {
    .Call(`_tsdiscov_cpp_pairwise_ccf`, X, max_lag)
}

#' Compute mutual information between two vectors - Rcpp version
#'
#' Histogram-based estimator of mutual information
#'
#' @param x Numeric vector
#' @param y Numeric vector
#' @param bins Number of bins for histogram
#' @return Mutual information estimate
#' @keywords internal
cpp_mutual_information <- function(x, y, bins = 10L) {
    .Call(`_tsdiscov_cpp_mutual_information`, x, y, bins)
}

#' Compute pairwise mutual information - Rcpp version
#'
#' Efficiently computes MI for all pairs of time series
#'
#' @param X Matrix (N x T) where rows are series, columns are timepoints
#' @param bins Number of bins for histogram
#' @return Vector of mutual information values for all pairs
#' @keywords internal
cpp_pairwise_mi <- function(X, bins = 10L) {
    .Call(`_tsdiscov_cpp_pairwise_mi`, X, bins)
}

#' Compute Shannon entropy from binned data - multivariate version
#'
#' @param x Numeric vector
#' @param bins Number of bins
#' @return Shannon entropy
#' @keywords internal
cpp_mv_shannon_entropy <- function(x, bins = 10L) {
    .Call(`_tsdiscov_cpp_mv_shannon_entropy`, x, bins)
}

#' Compute cross-spectral density for a pair of series - Rcpp version
#'
#' Uses FFT to compute cross-spectral density
#'
#' @param x First time series
#' @param y Second time series
#' @return List with coherence, phase, and CSD magnitude
#' @keywords internal
cpp_cross_spectral_density <- function(x, y) {
    .Call(`_tsdiscov_cpp_cross_spectral_density`, x, y)
}

#' Compute per-series statistics for diversity features - Rcpp version
#'
#' Efficiently computes univariate statistics for each series
#'
#' @param X Matrix (N x T) where rows are series
#' @return List with means, variances, ranges, skewness, kurtosis for each series
#' @keywords internal
cpp_series_statistics <- function(X) {
    .Call(`_tsdiscov_cpp_series_statistics`, X)
}

cpp_pacf <- function(x, max_lag = 20L) {
    .Call(`_tsdiscov_cpp_pacf`, x, max_lag)
}

cpp_pacf_features <- function(x, max_lag = 20L) {
    .Call(`_tsdiscov_cpp_pacf_features`, x, max_lag)
}

cpp_matrix_profile <- function(x, window_size = -1L) {
    .Call(`_tsdiscov_cpp_matrix_profile`, x, window_size)
}

cpp_friedrich_coefficients <- function(x, max_order = 3L) {
    .Call(`_tsdiscov_cpp_friedrich_coefficients`, x, max_order)
}

cpp_langevin_fixed_point <- function(x, max_order = 3L) {
    .Call(`_tsdiscov_cpp_langevin_fixed_point`, x, max_order)
}

cpp_recurrence_analysis <- function(x, threshold_percent = 0.1, min_line_length = 2L, max_points = 2000L) {
    .Call(`_tsdiscov_cpp_recurrence_analysis`, x, threshold_percent, min_line_length, max_points)
}

cpp_hurst_exponent <- function(x) {
    .Call(`_tsdiscov_cpp_hurst_exponent`, x)
}

cpp_stability <- function(x, window_size = 10L) {
    .Call(`_tsdiscov_cpp_stability`, x, window_size)
}

cpp_lumpiness <- function(x, window_size = 10L) {
    .Call(`_tsdiscov_cpp_lumpiness`, x, window_size)
}

cpp_shift_detection <- function(x, width = 10L) {
    .Call(`_tsdiscov_cpp_shift_detection`, x, width)
}

cpp_welch_power_low_freq <- function(x) {
    .Call(`_tsdiscov_cpp_welch_power_low_freq`, x)
}

cpp_spectral_centroid <- function(x) {
    .Call(`_tsdiscov_cpp_spectral_centroid`, x)
}

cpp_spectral_entropy <- function(x) {
    .Call(`_tsdiscov_cpp_spectral_entropy`, x)
}

cpp_fft_coefficients <- function(x, num_coef = 5L) {
    .Call(`_tsdiscov_cpp_fft_coefficients`, x, num_coef)
}

cpp_fft_aggregated <- function(x) {
    .Call(`_tsdiscov_cpp_fft_aggregated`, x)
}

cpp_welch_psd <- function(x, n_freq = 5L, window_size = -1L, overlap = 0.5) {
    .Call(`_tsdiscov_cpp_welch_psd`, x, n_freq, window_size, overlap)
}

#' Compute spectral shape descriptors
#'
#' @param x Numeric vector
#' @return Named list with spectral shape features
#' @export
cpp_spectral_shape <- function(x) {
    .Call(`_tsdiscov_cpp_spectral_shape`, x)
}

cpp_trend_strength <- function(trend, remainder) {
    .Call(`_tsdiscov_cpp_trend_strength`, trend, remainder)
}

cpp_seasonal_strength <- function(seasonal, remainder) {
    .Call(`_tsdiscov_cpp_seasonal_strength`, seasonal, remainder)
}

cpp_spike <- function(remainder) {
    .Call(`_tsdiscov_cpp_spike`, remainder)
}

cpp_linearity <- function(trend) {
    .Call(`_tsdiscov_cpp_linearity`, trend)
}

cpp_curvature <- function(trend) {
    .Call(`_tsdiscov_cpp_curvature`, trend)
}

cpp_number_peaks <- function(x, support = 3L) {
    .Call(`_tsdiscov_cpp_number_peaks`, x, support)
}

cpp_longest_strike_above_mean <- function(x) {
    .Call(`_tsdiscov_cpp_longest_strike_above_mean`, x)
}

cpp_longest_strike_below_mean <- function(x) {
    .Call(`_tsdiscov_cpp_longest_strike_below_mean`, x)
}

cpp_count_above_mean <- function(x) {
    .Call(`_tsdiscov_cpp_count_above_mean`, x)
}

cpp_count_below_mean <- function(x) {
    .Call(`_tsdiscov_cpp_count_below_mean`, x)
}

cpp_ratio_beyond_r_sigma <- function(x, r = 1.0) {
    .Call(`_tsdiscov_cpp_ratio_beyond_r_sigma`, x, r)
}

cpp_number_crossings <- function(x, m = 0.0) {
    .Call(`_tsdiscov_cpp_number_crossings`, x, m)
}

cpp_linear_trend <- function(x) {
    .Call(`_tsdiscov_cpp_linear_trend`, x)
}

cpp_mean_abs_change <- function(x) {
    .Call(`_tsdiscov_cpp_mean_abs_change`, x)
}

cpp_mean_change <- function(x) {
    .Call(`_tsdiscov_cpp_mean_change`, x)
}

cpp_mean_second_derivative <- function(x) {
    .Call(`_tsdiscov_cpp_mean_second_derivative`, x)
}

cpp_time_weighted_trend <- function(x, decay = 0.95) {
    .Call(`_tsdiscov_cpp_time_weighted_trend`, x, decay)
}

cpp_robust_trend <- function(x, max_pairs = 5000L) {
    .Call(`_tsdiscov_cpp_robust_trend`, x, max_pairs)
}

cpp_c3 <- function(x, lag = 1L) {
    .Call(`_tsdiscov_cpp_c3`, x, lag)
}

cpp_cid_ce <- function(x, normalize = TRUE) {
    .Call(`_tsdiscov_cpp_cid_ce`, x, normalize)
}

cpp_lempel_ziv_complexity <- function(x, bins = 10L) {
    .Call(`_tsdiscov_cpp_lempel_ziv_complexity`, x, bins)
}

cpp_index_mass_quantile <- function(x, q = 0.5) {
    .Call(`_tsdiscov_cpp_index_mass_quantile`, x, q)
}

cpp_mean_n_absolute_max <- function(x, number_of_maxima = 1L) {
    .Call(`_tsdiscov_cpp_mean_n_absolute_max`, x, number_of_maxima)
}

cpp_energy_ratio_by_chunks <- function(x, num_segments = 10L, segment_focus = 0L) {
    .Call(`_tsdiscov_cpp_energy_ratio_by_chunks`, x, num_segments, segment_focus)
}

cpp_change_quantiles <- function(x, ql = 0.0, qh = 1.0, isabs = FALSE, f_agg = "mean") {
    .Call(`_tsdiscov_cpp_change_quantiles`, x, ql, qh, isabs, f_agg)
}

cpp_fourier_entropy <- function(x, bins = 10L) {
    .Call(`_tsdiscov_cpp_fourier_entropy`, x, bins)
}

cpp_abs_energy <- function(x) {
    .Call(`_tsdiscov_cpp_abs_energy`, x)
}

cpp_sum_values <- function(x) {
    .Call(`_tsdiscov_cpp_sum_values`, x)
}

cpp_has_duplicate <- function(x) {
    .Call(`_tsdiscov_cpp_has_duplicate`, x)
}

cpp_has_duplicate_max <- function(x) {
    .Call(`_tsdiscov_cpp_has_duplicate_max`, x)
}

cpp_has_duplicate_min <- function(x) {
    .Call(`_tsdiscov_cpp_has_duplicate_min`, x)
}

cpp_percentage_reoccurring <- function(x) {
    .Call(`_tsdiscov_cpp_percentage_reoccurring`, x)
}

cpp_sum_reoccurring <- function(x) {
    .Call(`_tsdiscov_cpp_sum_reoccurring`, x)
}

cpp_ratio_unique_values <- function(x) {
    .Call(`_tsdiscov_cpp_ratio_unique_values`, x)
}

cpp_symmetry_looking <- function(x, r = 0.05) {
    .Call(`_tsdiscov_cpp_symmetry_looking`, x, r)
}

cpp_large_standard_deviation <- function(x, r = 0.25) {
    .Call(`_tsdiscov_cpp_large_standard_deviation`, x, r)
}

cpp_variance_larger_than_std <- function(x) {
    .Call(`_tsdiscov_cpp_variance_larger_than_std`, x)
}

cpp_adf_test <- function(x, max_lag = -1L, include_trend = TRUE) {
    .Call(`_tsdiscov_cpp_adf_test`, x, max_lag, include_trend)
}

